export const GAMES = [
  {
    id: 'nunchi-ten',
    name: '눈치 10단',
    description: '숫자 카드 심리전! 나보다 낮은 숫자를 낸 플레이어 수만큼 점수 획득',
    hostPath: '/games/nunchi-ten/host/',
    mobilePath: '/games/nunchi-ten/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🃏',
    thumbnailImg: '/games/nunchi-ten/assets/thumbnail.png',
  },
  {
    id: 'spin-battle',
    name: '팽이 배틀',
    description: '팽이를 충돌시켜 마지막까지 살아남아라!',
    hostPath: '/games/spin-battle/host/',
    mobilePath: '/games/spin-battle/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🌀',
  },
  {
    id: 'dice',
    name: '주사위',
    description: '모바일을 흔들어 주사위를 굴려라!',
    hostPath: '/games/dice/host/',
    mobilePath: '/games/dice/mobile/',
    minPlayers: 1,
    maxPlayers: 6,
    thumbnail: '🎲',
  },
  {
    id: 'digit-puzzle',
    name: 'Digit Puzzle',
    description: '4×4 슬라이딩 퍼즐 레이스! 먼저 완성하면 승리',
    hostPath: '/games/digit-puzzle/host/',
    mobilePath: '/games/digit-puzzle/mobile/',
    minPlayers: 2,
    maxPlayers: 4,
    thumbnail: '🧩',
  },
];
