export const GAMES = [
  {
    id: 'nunchi-ten',
    name: '눈치 10단',
    description: '숫자 카드 심리전! 나보다 낮은 숫자를 낸 플레이어 수만큼 점수 획득',
    hostPath: '/games/nunchi-ten/host/',
    mobilePath: '/games/nunchi-ten/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🃏',
    thumbnailImg: '/games/nunchi-ten/assets/thumbnail.png',
    group: 'multi',
  },
  {
    id: 'spin-battle',
    name: '팽이 배틀',
    description: '팽이를 충돌시켜 마지막까지 살아남아라!',
    hostPath: '/games/spin-battle/host/',
    mobilePath: '/games/spin-battle/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🌀',
    group: 'multi',
  },
  {
    id: 'dice',
    name: '주사위',
    description: '모바일을 흔들어 주사위를 굴려라!',
    hostPath: '/games/dice/host/',
    mobilePath: '/games/dice/mobile/',
    minPlayers: 1,
    maxPlayers: 6,
    thumbnail: '🎲',
    group: 'multi',
  },
  {
    id: 'digit-puzzle',
    name: 'Digit Puzzle',
    description: '4×4 슬라이딩 퍼즐 레이스! 먼저 완성하면 승리',
    hostPath: '/games/digit-puzzle/host/',
    mobilePath: '/games/digit-puzzle/mobile/',
    minPlayers: 2,
    maxPlayers: 4,
    thumbnail: '🧩',
    group: 'multi',
  },
  {
    id: 'give-you-fire',
    name: 'Give You Fire',
    description: '배틀 테트리스! 라인 클리어로 상대방을 불태워라 🔥',
    hostPath: '/games/give-you-fire/host/',
    mobilePath: '/games/give-you-fire/mobile/',
    minPlayers: 1,
    maxPlayers: 4,
    thumbnail: '🔥',
    group: 'multi',
  },
  {
    id: 'relay-drawing',
    name: '그림 릴레이',
    description: '스마트폰을 스케치북 삼아 제시어를 그리고 맞히는 왁자지껄 파티 게임 🎨',
    hostPath: '/games/relay-drawing/host/',
    mobilePath: '/games/relay-drawing/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🎨',
    group: 'multi',
  },
  {
    id: 'dobble',
    name: 'Dobble',
    description: '중앙 카드와 내 카드의 같은 심볼을 먼저 찾아 탭! 2~6인 스피드 게임',
    hostPath: '/games/dobble/host/',
    mobilePath: '/games/dobble/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🎯',
    group: 'multi',
  },
  {
    id: 'dixit',
    name: 'Dixit',
    description: '상상력과 스토리텔링의 카드 게임! 힌트를 듣고 이야기꾼의 카드를 찾아보세요.',
    hostPath: '/games/dixit/host/',
    mobilePath: '/games/dixit/mobile/',
    minPlayers: 3,
    maxPlayers: 8,
    thumbnail: '🖼️',
    group: 'multi',
  },
  {
    id: 'trading-battle',
    name: '천하제일단타대회',
    description: '실제 주식 차트로 매매 배틀! 제한 시간 내 최고 수익률을 달성하라 📈',
    hostPath: '/games/trading-battle/host/',
    mobilePath: '/games/trading-battle/mobile/',
    minPlayers: 2,
    maxPlayers: 4,
    thumbnail: '📈',
    group: 'multi',
  },
  {
    id: 'omok',
    name: '오목',
    description: 'AI와 1:1 오목 대결! 13×13 바둑판에서 먼저 5개를 연결하면 승리',
    hostPath: '/games/omok/',
    thumbnail: '⚫',
    group: 'solo',
  },
  {
    id: 'hidden-agent',
    name: '스파이를 찾아라!',
    description: '서로의 단어를 유추해 숨어있는 스파이를 검거하라! 3인 이상 심리 보드게임 🕵️‍♂️',
    hostPath: '/games/hidden-agent/host/',
    mobilePath: '/games/hidden-agent/mobile/',
    minPlayers: 3,
    maxPlayers: 8,
    thumbnail: '🕵️‍♂️',
    group: 'multi',
  },
];
