export const GAMES = [
  {
    id: 'nunchi-ten',
    name: '눈치 10단',
    description: '숫자 카드 심리전! 나보다 낮은 숫자를 낸 플레이어 수만큼 점수 획득',
    hostPath: '/games/nunchi-ten/host/',
    mobilePath: '/games/nunchi-ten/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🃏',
    thumbnailImg: '/games/nunchi-ten/assets/thumbnail.png',
    group: 'multi',
  },
  {
    id: 'spin-battle',
    name: '팽이 배틀',
    description: '팽이를 충돌시켜 마지막까지 살아남아라!',
    hostPath: '/games/spin-battle/host/',
    mobilePath: '/games/spin-battle/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🌀',
    group: 'multi',
  },
  {
    id: 'dice',
    name: '주사위',
    description: '모바일을 흔들어 주사위를 굴려라!',
    hostPath: '/games/dice/host/',
    mobilePath: '/games/dice/mobile/',
    minPlayers: 1,
    maxPlayers: 6,
    thumbnail: '🎲',
    group: 'multi',
  },
  {
    id: 'digit-puzzle',
    name: 'Digit Puzzle',
    description: '4×4 슬라이딩 퍼즐 레이스! 먼저 완성하면 승리',
    hostPath: '/games/digit-puzzle/host/',
    mobilePath: '/games/digit-puzzle/mobile/',
    minPlayers: 2,
    maxPlayers: 4,
    thumbnail: '🧩',
    group: 'multi',
  },
  {
    id: 'give-you-fire',
    name: 'Give You Fire',
    description: '배틀 테트리스! 라인 클리어로 상대방을 불태워라 🔥',
    hostPath: '/games/give-you-fire/host/',
    mobilePath: '/games/give-you-fire/mobile/',
    minPlayers: 1,
    maxPlayers: 4,
    thumbnail: '🔥',
    group: 'multi',
  },
  {
    id: 'relay-drawing',
    name: '그림 릴레이',
    description: '스마트폰을 스케치북 삼아 제시어를 그리고 맞히는 왁자지껄 파티 게임 🎨',
    hostPath: '/games/relay-drawing/host/',
    mobilePath: '/games/relay-drawing/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🎨',
    group: 'multi',
  },
  {
    id: 'dobble',
    name: 'Dobble',
    description: '중앙 카드와 내 카드의 같은 심볼을 먼저 찾아 탭! 2~6인 스피드 게임',
    hostPath: '/games/dobble/host/',
    mobilePath: '/games/dobble/mobile/',
    minPlayers: 2,
    maxPlayers: 6,
    thumbnail: '🎯',
    group: 'multi',
  },
  {
    id: 'dixit',
    name: 'Dixit',
    description: '상상력과 스토리텔링의 카드 게임! 힌트를 듣고 이야기꾼의 카드를 찾아보세요.',
    hostPath: '/games/dixit/host/',
    mobilePath: '/games/dixit/mobile/',
    minPlayers: 3,
    maxPlayers: 8,
    thumbnail: '🖼️',
    group: 'multi',
  },
  {
    id: 'trading-battle',
    name: '천하제일단타대회',
    description: '실제 주식 차트로 매매 배틀! 제한 시간 내 최고 수익률을 달성하라 📈',
    hostPath: '/games/trading-battle/host/',
    mobilePath: '/games/trading-battle/mobile/',
    minPlayers: 2,
    maxPlayers: 4,
    thumbnail: '📈',
    group: 'multi',
  },
  {
    id: 'omok',
    name: '오목',
    description: '모바일로 1:1 오목 대결! 13×13 바둑판에서 먼저 5개를 연결하면 승리 ⚫⚪',
    hostPath: '/games/omok/host/',
    mobilePath: '/games/omok/mobile/',
    minPlayers: 2,
    maxPlayers: 2,
    thumbnail: '⚫',
    group: 'multi',
  },
  {
    id: 'hidden-agent',
    name: '스파이를 찾아라!',
    description: '서로의 단어를 유추해 숨어있는 스파이를 검거하라! 3인 이상 심리 보드게임 🕵️‍♂️',
    hostPath: '/games/hidden-agent/host/',
    mobilePath: '/games/hidden-agent/mobile/',
    minPlayers: 3,
    maxPlayers: 8,
    thumbnail: '🕵️‍♂️',
    group: 'multi',
  },
  {
    id: 'pirate-plunder',
    name: '해적의 전리품 (Pirates Plunder)',
    description: '동맹인가 배신인가! 협상하여 금화를 나눌지 독차지할지 선택하는 고도의 심리 게임 🏴‍☠️',
    hostPath: '/games/pirate-plunder/host/',
    mobilePath: '/games/pirate-plunder/mobile/',
    minPlayers: 3,
    maxPlayers: 8,
    thumbnail: '🏴‍☠️',
    group: 'multi',
  },
  {
    id: 'spectrum-mind',
    name: '스펙트럼 마인드',
    description: '생각의 주파수를 맞추어라! 제시어와 타겟 다이얼의 위치를 조율하는 심리 파티 게임 🎯',
    hostPath: '/games/spectrum-mind/host/',
    mobilePath: '/games/spectrum-mind/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🎯',
    group: 'multi',
  },
  {
    id: 'panic-cockpit',
    name: '패닉 콕핏 (Panic Cockpit)',
    description: '서로 소통하며 명령을 내리는 실시간 우주선 탈출 협동 게임! 2~8인용 🚀',
    hostPath: '/games/panic-cockpit/host/',
    mobilePath: '/games/panic-cockpit/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🚀',
    group: 'multi',
  },
  {
    id: 'herd-logic',
    name: '허드 로직 (Herd Logic)',
    description: '가장 평범한 대답을 골라라! 다수파와 주파수를 맞추는 엉뚱유쾌 심리 동조 게임 🐄',
    hostPath: '/games/herd-logic/host/',
    mobilePath: '/games/herd-logic/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🐄',
    group: 'multi',
  },
  {
    id: 'trivia-vegas',
    name: '트리비아 베가스 (Trivia Vegas)',
    description: '명작 퀴즈 베팅 게임의 귀환! 숫자로 상식을 겨루고 근접 답안에 칩을 거는 베팅 퀴즈 파티 🎲',
    hostPath: '/games/trivia-vegas/host/',
    mobilePath: '/games/trivia-vegas/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🎲',
    group: 'multi',
  },
  {
    id: 'dimension-weaver',
    name: '디멘션 위버 (Dimension Weaver)',
    description: '비대칭 시공간 협동! 각자의 폰에 다른 차원의 위협이 나타나는 실시간 차원 조율 파티 게임 🌀',
    hostPath: '/games/dimension-weaver/host/',
    mobilePath: '/games/dimension-weaver/mobile/',
    minPlayers: 2,
    maxPlayers: 8,
    thumbnail: '🌀',
    group: 'multi',
  },
];
