name: Windows Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deployment script
        shell: cmd
        run: |
          cd /d D:\Source\connect_dise
          git fetch origin main
          git reset --hard origin/main
          call D:\Source\connect_dise\deploy.bat
