name: Windows Auto Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Run deployment script
        run: |
          cd D:\Source\connect_dise
          git fetch origin main
          git reset --hard origin/main
          .\deploy.bat
